### ISSUE TITLE
Build NPM package

### ISSUE THREAD

**Issue by RudeySH** [joseprio/xBRjs#1]
This could be useful when distributed as an NPM package.

**Comment by joseprio** [comment]
I was a bit wary on offering this as an NPM package because of two reasons:
- There's already an XBR implementation (`super-xbr`)
- The alpha channel handling was buggy

After I fixed the alpha channel handling in #2 , I'm quite confident on the value of this library, so I'll refactor things a bit and publish it on NPM.

While it's similar to `super-xbr`, the algorithms are a bit different, and my version supports the 3x mode.

Thanks a lot for your suggestion!!

**Comment by joseprio** [comment]
Ok, it's published now:
https://www.npmjs.com/package/xbr-js

**Comment by RudeySH** [comment]
Thanks!
